/**
 * Markdown rendering of a conformance run.
 *
 * The report is committed, so it is rendered from committed data only — the fixture, the
 * ledger snapshot and the corpus — and never from the wall clock. `--check` can then assert
 * that replaying the fixture reproduces the committed report byte for byte.
 */

import type { Case } from './corpus.ts';
import { EXECUTION_LEVEL_LEDGER_ROWS, REQUIRED_FEATURES, featureCoverage, ledgerCoverage } from './corpus.ts';
import type { Difference, Json, Outcome } from './canonical.ts';
import { digest, stableStringify } from './canonical.ts';
import type { Classification, Comparison } from './classify.ts';
import type { Ledger, Provenance, RunResult } from './compare.ts';

export type { Ledger, Provenance, RunResult } from './compare.ts';

const escapeCell = (text: string): string => text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const code = (text: string): string => '`' + escapeCell(text.replace(/`/g, 'ˋ')) + '`';
const queryCell = (query: string): string => (query === '' ? '_(empty string)_' : code(truncate(query, 70)));

function truncate(text: string, limit: number): string {
	return text.length <= limit ? text : `${text.slice(0, limit - 1)}…`;
}

function describeOutcome(outcome: Outcome): string {
	switch (outcome.status) {
		case 'parsed': return 'parsed';
		case 'rejected': return 'rejected';
		case 'deferred-error': return 'rejected (deferred)';
		case 'timeout': return `timeout after ${outcome.ms}ms`;
		case 'adapter-gap': return 'adapter gap';
		case 'harness-error': return 'harness error';
	}
}

export function canonicalOf(outcome: Outcome): Json | undefined {
	return outcome.status === 'parsed' || outcome.status === 'deferred-error' ? outcome.canonical : undefined;
}

function outcomeDetail(outcome: Outcome): string {
	const json = canonicalOf(outcome);
	if (json !== undefined) {
		const body = '```json\n' + stableStringify(json, 2) + '\n```';
		return outcome.status === 'deferred-error' ? `> ${escapeCell(outcome.error)}\n\n${body}` : body;
	}
	if (outcome.status === 'rejected') return `> ${escapeCell(outcome.error)}`;
	if (outcome.status === 'adapter-gap' || outcome.status === 'harness-error') return `> ${escapeCell(outcome.error)}`;
	if (outcome.status === 'timeout') return `> timed out after ${outcome.ms}ms`;
	return '';
}

/** Days between two ISO timestamps, floored — a stable function of committed data. */
function daysBetween(from: string, to: string): number {
	return Math.floor((Date.parse(to) - Date.parse(from)) / 86_400_000);
}

/** Divergences are grouped by what explains them: a ledger row, or the rule that matched. */
function groupKey(classification: Classification): string {
	switch (classification.verdict) {
		case 'ledger': return `row ${classification.row}`;
		case 'new':
		case 'reference-bug': return classification.rule;
		default: return classification.verdict;
	}
}

export function renderReport(run: RunResult): string {
	const { comparisons, ledger, provenance } = run;
	const lines: string[] = [];
	const write = (text = ''): void => void lines.push(text);

	const byVerdict = <T extends Classification['verdict']>(verdict: T) =>
		comparisons.filter((comparison) => comparison.classification.verdict === verdict);

	const agrees = byVerdict('agrees');
	const ledgerHits = byVerdict('ledger');
	const news = byVerdict('new');
	const referenceBugs = byVerdict('reference-bug');
	const unclassified = byVerdict('unclassified');
	const divergences = comparisons.length - agrees.length;

	write('# RQL 2.0 differential conformance report');
	write();
	write('Generated by `npm run conformance` — do not edit by hand.');
	write();
	write('Every corpus query is parsed by both Harper’s REST query parser and the RQL 2.0');
	write('reference parser, Harper’s output is mapped to the canonical model (§6) by');
	write('`conformance/harperAdapter.ts`, and the two canonical results are compared. Every');
	write('disagreement is classified below; an unclassified disagreement fails the run.');
	write();
	write('### How to read this');
	write();
	write('- A disagreement is classified by RULE, not case by case — the rules live in');
	write('  `conformance/classify.ts` and each names the witnesses it covers.');
	write('- The verdict names **the side that has to change** for the two parsers to agree');
	write('  *conformantly*. Where both deviate from the spec, the rationale says so.');
	write('- Harper’s uninterpreted values (§5.2.2) are stripped from a case’s difference list');
	write('  before the other rules see it, so one pervasive divergence does not mask the rest.');
	write('  A case where they were stripped is marked "+ uninterpreted values".');
	write('- Scope: this compares PARSE results only. Value coercion against a table’s declared');
	write('  attribute types, comparator evaluation and result materialization all happen later,');
	write('  in `resources/Table.ts`, and no case here can witness them.');
	write();

	write('## Provenance');
	write();
	write('| | |');
	write('|---|---|');
	write(`| Harper commit | ${code(provenance.harper.commit)}${provenance.harper.describe ? ` (${escapeCell(provenance.harper.describe)})` : ''}${provenance.harper.dirty ? ' **+ uncommitted changes**' : ''} |`);
	write(`| Harper version | ${provenance.harper.version ? code(provenance.harper.version) : '_unknown_'} |`);
	write(
		`| Reference parser at recording | ${code(provenance.reference.commit)}${provenance.reference.describe ? ` (${escapeCell(provenance.reference.describe)})` : ''}${provenance.reference.dirty ? ' **+ uncommitted changes**' : ''} |`
	);
	write(`| Fixture recorded | ${provenance.recordedAt} |`);
	write(`| Recorded on Node | ${code(provenance.node)} |`);
	write(`| Corpus digest | ${code(provenance.corpusDigest)} |`);
	write(`| Ledger snapshot | [${escapeCell(ledger.source.repo)}#${ledger.source.issue}](${ledger.source.url}), ${ledger.rows.length} rows, fetched ${ledger.fetchedAt} |`);
	const drift = daysBetween(ledger.fetchedAt, provenance.recordedAt);
	write(
		`| Snapshot vs fixture | snapshot fetched ${drift === 0 ? 'the same day as' : drift > 0 ? `${drift} day(s) before` : `${-drift} day(s) after`} the fixture recording |`
	);
	write();
	write('The ledger snapshot is a cache. [' + escapeCell(`${ledger.source.repo}#${ledger.source.issue}`) + '](' + ledger.source.url + ') stays canonical —');
	write('refresh with `npm run conformance:refresh-ledger` before trusting a classification.');
	write();
	write('Harper’s side of every comparison below is the recorded fixture, so it is exactly the');
	write('commit named above. The reference side is parsed live at replay time by the parser in the');
	write('working tree, which the row above dates only as of the recording: change `src/` and');
	write('`npm run conformance:check` fails until the report is regenerated, and');
	write('`npm run conformance:record` re-stamps the row.');
	write();

	write('## Totals');
	write();
	write('| Outcome | Cases |');
	write('|---|---:|');
	write(`| Corpus size | ${comparisons.length} |`);
	write(`| Agree (identical canonical result, or both reject) | ${agrees.length} |`);
	write(`| **Diverge** | **${divergences}** |`);
	write(`| — classified to a ledger row | ${ledgerHits.length} |`);
	write(`| — NEW divergence (proposed rows below) | ${news.length} |`);
	write(`| — reference-parser bug | ${referenceBugs.length} |`);
	write(`| — **unclassified (must be 0)** | **${unclassified.length}** |`);
	write();

	const statusCounts = new Map<string, number>();
	for (const comparison of comparisons) {
		const key = `${describeOutcome(comparison.ref)} / ${describeOutcome(comparison.harper)}`;
		statusCounts.set(key, (statusCounts.get(key) ?? 0) + 1);
	}
	write('| Reference outcome / Harper outcome | Cases |');
	write('|---|---:|');
	for (const [key, count] of [...statusCounts].sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0])))
		write(`| ${key} | ${count} |`);
	write();

	write('## Grammar feature coverage');
	write();
	write('Each corpus case carries the grammar features it exercises; every feature of §4–§5.7');
	write('is required to have at least one case.');
	write();
	write('| Feature | Cases | Agree | Diverge |');
	write('|---|---:|---:|---:|');
	const verdictById = new Map(comparisons.map((comparison) => [comparison.case.id, comparison.classification.verdict]));
	const coverage = featureCoverage(comparisons.map((comparison) => comparison.case));
	for (const feature of [...coverage.keys()].sort()) {
		const cases = coverage.get(feature) ?? [];
		const agreeCount = cases.filter((item) => verdictById.get(item.id) === 'agrees').length;
		const required = (REQUIRED_FEATURES as readonly string[]).includes(feature);
		write(`| ${code(feature)}${required ? '' : ' _(extra)_'} | ${cases.length} | ${agreeCount} | ${cases.length - agreeCount} |`);
	}
	write();

	write('## Divergence-ledger coverage');
	write();
	write(`Rows of [${escapeCell(`${ledger.source.repo}#${ledger.source.issue}`)}](${ledger.source.url}), and the corpus cases that witness them.`);
	write('A row marked _execution-level_ describes behavior after parsing, which a parser-only');
	write('harness cannot observe.');
	write();
	write('| Row | Class | Divergence | Witnesses | Observed |');
	write('|---:|---|---|---:|---|');
	const witnesses = ledgerCoverage(comparisons.map((comparison) => comparison.case));
	const ledgerObserved = new Map<number, number>();
	for (const comparison of comparisons)
		if (comparison.classification.verdict === 'ledger')
			ledgerObserved.set(comparison.classification.row, (ledgerObserved.get(comparison.classification.row) ?? 0) + 1);
	const deferredQueries = new Set(run.deferred.map((observation) => observation.case.query));
	const otherRules = new Map<number, Set<string>>();
	for (const comparison of comparisons) {
		const verdict = comparison.classification;
		if (verdict.verdict !== 'new' && verdict.verdict !== 'reference-bug') continue;
		const rule = verdict.rule;
		for (const row of comparison.case.ledger ?? []) {
			const bucket = otherRules.get(row) ?? new Set<string>();
			bucket.add(rule);
			otherRules.set(row, bucket);
		}
	}
	for (const row of ledger.rows) {
		const cases = witnesses.get(row.row) ?? [];
		const observed = ledgerObserved.get(row.row) ?? 0;
		const executionLevel = EXECUTION_LEVEL_LEDGER_ROWS[row.row];
		let state: string;
		if (observed > 0) state = `confirmed — ${observed} diverging case(s)`;
		else if (executionLevel) state = `_execution-level_ — ${escapeCell(executionLevel)}`;
		else if (cases.some((item) => deferredQueries.has(item.query)))
			state = 'confirmed in deferred-error mode — see below';
		else if (otherRules.has(row.row))
			state = `witnessed; the difference observed is classified as ${[...(otherRules.get(row.row) ?? [])].map(code).join(', ')}`;
		else if (cases.length > 0) state = 'exercised; the adapter maps it to the canonical model, so nothing differs';
		else state = 'no corpus witness';
		write(`| ${row.row} | ${escapeCell(row.class)} | ${escapeCell(truncate(row.divergence, 90))} | ${cases.length} | ${state} |`);
	}
	write();

	const sections: [string, string, typeof comparisons][] = [
		['NEW divergences', 'Not yet in Harper’s ledger. Each block proposes a row to add — the spec is not edited here.', news],
		['Divergences matching an existing ledger row', 'Already tracked; cited by row number.', ledgerHits],
		['Reference-parser bugs', 'The reference implementation, not Harper, is wrong here.', referenceBugs],
		['Unclassified', 'Every entry here is a hole in `conformance/classify.ts` and fails the run.', unclassified],
	];

	for (const [title, blurb, group] of sections) {
		write(`## ${title}`);
		write();
		write(blurb);
		write();
		if (group.length === 0) {
			write('_None._');
			write();
			continue;
		}
		const grouped = new Map<string, typeof group>();
		for (const comparison of group) {
			const key = groupKey(comparison.classification);
			const bucket = grouped.get(key);
			if (bucket) bucket.push(comparison);
			else grouped.set(key, [comparison]);
		}
		for (const [key, bucket] of grouped) {
			const first = bucket[0].classification;
			write(`### ${key} — ${bucket.length} case(s)`);
			write();
			if (first.verdict === 'ledger') {
				const row = ledger.rows.find((candidate) => candidate.row === first.row);
				if (row) {
					write(`Ledger row ${row.row} (${row.class}): ${row.divergence}`);
					write();
					write(`Tracked action: ${row.action}`);
					write();
				}
				write(first.rationale);
				write();
			} else if (first.verdict === 'new') {
				write(first.rationale);
				write();
				write('**Proposed ledger row**');
				write();
				write('| Divergence | Class | Action |');
				write('|---|---|---|');
				write(`| ${escapeCell(first.proposal.divergence)} | ${escapeCell(first.proposal.class)} | ${escapeCell(first.proposal.action)} |`);
				write();
			} else if (first.verdict === 'reference-bug') {
				write(first.rationale);
				write();
			}
			write('| Query | Reference | Harper (adapted) |');
			write('|---|---|---|');
			for (const comparison of bucket)
				write(
					`| ${queryCell(comparison.case.query)} | ${describeOutcome(comparison.ref)} | ${describeOutcome(comparison.harper)}` +
						`${comparison.alsoUninterpretedValues ? ' + uninterpreted values' : ''} |`
				);
			write();
			const sample = bucket[0];
			write(`<details><summary>Worked example: ${queryCell(sample.case.query)}</summary>`);
			write();
			write('Reference:');
			write();
			write(outcomeDetail(sample.ref));
			write();
			write('Harper, adapted:');
			write();
			write(outcomeDetail(sample.harper));
			write();
			if (sample.differences.length > 0) {
				write('Differences:');
				write();
				write('| At | Kind | Reference | Harper |');
				write('|---|---|---|---|');
				for (const difference of sample.differences.slice(0, 12))
					write(
						`| ${code(difference.at || '/')} | ${difference.kind} | ${difference.ref === undefined ? '—' : code(stableStringify(difference.ref))} | ${difference.harper === undefined ? '—' : code(stableStringify(difference.harper))} |`
					);
				if (sample.differences.length > 12) write(`| … | ${sample.differences.length - 12} more | | |`);
				write();
			}
			write('</details>');
			write();
		}
	}

	write('## Deferred-error mode (ledger rows 8 and 9)');
	write();
	write('Harper’s production entry point is `new RequestTarget("?" + query)`, which never throws:');
	write('a parse error is deferred into `parseError` for the request pipeline to raise (§6.1');
	write('permits this). These cases show what that path produces where the throwing entry point');
	write('rejects — including row 9, where a reserved call name is rejected *and* still falls');
	write('through into `sort`.');
	write();
	write('The `#` column fingerprints the full produced value, so a change past the truncation');
	write('point still changes the committed bytes and `conformance:check` still catches it.');
	write();
	write('| Query | Reference (deferred) | Harper (deferred) | Harper still produced | # |');
	write('|---|---|---|---|---|');
	for (const observation of run.deferred) {
		const produced = canonicalOf(observation.harper);
		write(
			`| ${queryCell(observation.case.query)} | ${describeOutcome(observation.ref)} | ${describeOutcome(observation.harper)} | ` +
				`${produced === undefined ? '—' : code(truncate(stableStringify(produced), 90))} | ${produced === undefined ? '—' : code(digest(produced))} |`
		);
	}
	write();

	write('## Every case');
	write();
	write('All ' + comparisons.length + ' corpus cases, in corpus order, with the verdict applied to each.');
	write();
	write('| # | Query | Features | Reference | Harper | Verdict |');
	write('|---:|---|---|---|---|---|');
	comparisons.forEach((comparison, index) => {
		const verdict = comparison.classification;
		const label =
			verdict.verdict === 'agrees'
				? 'agrees'
				: verdict.verdict === 'ledger'
					? `ledger row ${verdict.row}`
					: verdict.verdict === 'new'
						? `NEW (${verdict.rule})`
						: verdict.verdict === 'reference-bug'
							? `reference bug (${verdict.rule})`
							: '**UNCLASSIFIED**';
		write(
			`| ${index + 1} | ${queryCell(comparison.case.query)} | ${comparison.case.features.map(code).join(' ')} | ${describeOutcome(comparison.ref)} | ` +
				`${describeOutcome(comparison.harper)}${comparison.alsoUninterpretedValues ? ' + uninterpreted values' : ''} | ${label} |`
		);
	});
	write();

	return lines.join('\n');
}

export type { Difference };
